lab50:
  window:
    - editor
    - readme
    - terminal
    - x

  files:
    - !include tracy.py
    
submit50:
  files: &files
    - !exclude "*"
    - !require tracy.py
      
check50:
  files: *files
