lab50:
    window:
        - editor
        - readme
        - terminal
        - x

    files:
        - !exclude "*"
        - !include tracy.py
        - !include setup/setup.py

submit50:
    files: &files
        - !require tracy.py
        - !require setup.py

check50:
    files: *files
