lab50:
    window:
        - editor
        - readme
        - terminal
        - x

    files:
        - !exclude "*"
        - !include tracy.py
        - !include __setup.py

submit50:
    files: &files
        - !require tracy.py
        - !require __setup.py

check50:
    files: *files

    checks: "./admin/__init__.py"
