lab50:
    window:
        - editor
        - readme
        - terminal
        - x

    files:
        - !exclude "*"
        - !include main.py
        - !include __setup.py
        - !include end_world.png

submit50:
    files: &files
        - !require main.py
        - !require __setup.py

check50:
    files: *files

    checks: "./admin/__init__.py"
